# Generated by Django 3.1.1 on 2020-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200914_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(3, '3'), (4, '4'), (5, '5'), (2, '2'), (1, '1')], default=None, null=True),
        ),
    ]
