# Generated by Django 3.1.1 on 2020-09-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200915_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(5, '5'), (4, '4'), (2, '2'), (1, '1'), (3, '3')], default=None, null=True),
        ),
    ]
