# Generated by Django 3.1.1 on 2020-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200915_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(1, '1'), (5, '5'), (2, '2'), (3, '3'), (4, '4')], default=None, null=True),
        ),
    ]
