# Generated by Django 3.1.1 on 2020-09-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200915_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(3, '3'), (5, '5'), (2, '2'), (4, '4'), (1, '1')], default=None, null=True),
        ),
    ]
