# Generated by Django 3.1.1 on 2020-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200915_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(4, '4'), (3, '3'), (1, '1'), (5, '5'), (2, '2')], default=None, null=True),
        ),
    ]
