# Generated by Django 3.1.1 on 2020-09-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200916_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(1, '1'), (4, '4'), (3, '3'), (2, '2'), (5, '5')], default=None, null=True),
        ),
    ]
