# Generated by Django 3.1.1 on 2020-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200916_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(4, '4'), (2, '2'), (5, '5'), (1, '1'), (3, '3')], default=None, null=True),
        ),
    ]
