# Generated by Django 3.1.1 on 2020-09-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200919_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(1, '1'), (4, '4'), (3, '3'), (2, '2'), (5, '5')], default=None, null=True),
        ),
    ]
