# Generated by Django 3.1.1 on 2020-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200919_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(1, '1'), (3, '3'), (5, '5'), (2, '2'), (4, '4')], default=None, null=True),
        ),
    ]
