# Generated by Django 3.1.1 on 2020-09-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200919_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(1, '1'), (5, '5'), (4, '4'), (2, '2'), (3, '3')], default=None, null=True),
        ),
    ]
