# Generated by Django 3.1.1 on 2020-09-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200919_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(5, '5'), (3, '3'), (4, '4'), (1, '1'), (2, '2')], default=None, null=True),
        ),
    ]
