# Generated by Django 3.1.1 on 2020-09-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200919_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(1, '1'), (4, '4'), (5, '5'), (2, '2'), (3, '3')], default=None, null=True),
        ),
    ]
