# Generated by Django 3.1.1 on 2020-09-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200920_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(4, '4'), (1, '1'), (3, '3'), (2, '2'), (5, '5')], default=None, null=True),
        ),
    ]
