# Generated by Django 3.1.1 on 2020-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200920_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(3, '3'), (1, '1'), (5, '5'), (4, '4'), (2, '2')], default=None, null=True),
        ),
    ]
