# Generated by Django 3.1.1 on 2020-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200920_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(4, '4'), (5, '5'), (2, '2'), (3, '3'), (1, '1')], default=None, null=True),
        ),
    ]
