# Generated by Django 3.1.1 on 2020-09-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200920_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(2, '2'), (4, '4'), (3, '3'), (1, '1'), (5, '5')], default=None, null=True),
        ),
    ]
