# Generated by Django 3.1.1 on 2020-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200921_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(2, '2'), (5, '5'), (1, '1'), (4, '4'), (3, '3')], default=None, null=True),
        ),
    ]
