# Generated by Django 3.1.1 on 2020-09-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200921_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, choices=[(5, '5'), (2, '2'), (1, '1'), (3, '3'), (4, '4')], default=None, null=True),
        ),
    ]
