# Generated by Django 3.1.1 on 2020-09-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_lecturecategory_lecturesubcategory_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturesubcategory',
        ),
    ]
