# Generated by Django 3.1.1 on 2020-09-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_cons_pros_review_reviewcons_reviewpros_user_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userinfo', models.OneToOneField(db_column='userIdx', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lecture.userinfo')),
                ('userid', models.CharField(db_column='userId', max_length=45)),
                ('userpwd', models.CharField(db_column='userPwd', max_length=45)),
                ('gender', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=20)),
                ('school', models.CharField(blank=True, max_length=30, null=True)),
                ('job', models.CharField(blank=True, max_length=1, null=True)),
                ('major', models.CharField(blank=True, max_length=1, null=True)),
                ('isblocked', models.CharField(db_column='isBlocked', max_length=1)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField()),
                ('subcategory', models.IntegerField(db_column='subCategory')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
