# Generated by Django 3.1.1 on 2020-09-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_auto_20200919_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likesforqna',
            fields=[
                ('likesforqnaidx', models.AutoField(db_column='likesForQnAIdx', primary_key=True, serialize=False)),
                ('useridx', models.IntegerField(db_column='userIdx')),
                ('qnaidx', models.IntegerField(db_column='qnaIdx')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'likesForQnA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likesforreview',
            fields=[
                ('likesforreview', models.AutoField(db_column='likesForReview', primary_key=True, serialize=False)),
                ('useridx', models.IntegerField(db_column='userIdx')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'likesForReview',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
