# Generated by Django 3.1.1 on 2020-09-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_auto_20200920_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelidx', models.AutoField(db_column='levelIdx', primary_key=True, serialize=False)),
                ('levelname', models.CharField(blank=True, db_column='levelName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'level',
                'managed': False,
            },
        ),
    ]
