# Generated by Django 3.1.1 on 2020-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentidx', models.AutoField(db_column='commentIdx', primary_key=True, serialize=False)),
                ('useridx', models.CharField(db_column='userIdx', max_length=45)),
                ('lectureidx', models.CharField(db_column='lectureIdx', max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('qnades', models.TextField(db_column='qnaDes')),
                ('parentidx', models.IntegerField(blank=True, db_column='parentIdx', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
                ('isblocked', models.CharField(db_column='isBlocked', max_length=1)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commentimage',
            fields=[
                ('commentimageidx', models.AutoField(db_column='commentImageIdx', primary_key=True, serialize=False)),
                ('commentidx', models.IntegerField(db_column='commentIdx')),
                ('imageurl', models.TextField(db_column='imageUrl')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'commentImage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('qnaidx', models.AutoField(db_column='qnaIdx', primary_key=True, serialize=False)),
                ('useridx', models.IntegerField(db_column='userIdx')),
                ('lectureidx', models.IntegerField(db_column='lectureIdx')),
                ('title', models.TextField()),
                ('qnades', models.TextField(db_column='qnaDes')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
                ('isblocked', models.CharField(db_column='isBlocked', max_length=1)),
            ],
            options={
                'db_table': 'qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qnaimage',
            fields=[
                ('qnaimageidx', models.AutoField(db_column='qnaImageIdx', primary_key=True, serialize=False)),
                ('qnaidx', models.IntegerField(db_column='qnaIdx')),
                ('imgurl', models.TextField(db_column='imgUrl')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'qnaImage',
                'managed': False,
            },
        ),
    ]
