# Generated by Django 3.1.1 on 2020-09-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryinterest',
            fields=[
                ('categoryinterestidx', models.AutoField(db_column='categoryInterestIdx', primary_key=True, serialize=False)),
                ('useridx', models.IntegerField(db_column='userIdx')),
                ('categoryidx', models.IntegerField(db_column='categoryIdx')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'categoryInterest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lectureinfo',
            fields=[
                ('lectureidx', models.AutoField(db_column='lectureIdx', primary_key=True, serialize=False)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=4)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'lectureInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategoryinterest',
            fields=[
                ('subcategoryinterestidx', models.AutoField(db_column='subCategoryInterestIdx', primary_key=True, serialize=False)),
                ('useridx', models.IntegerField(db_column='userIdx')),
                ('subcategotyidx', models.IntegerField(db_column='subCategotyIdx')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'subCategoryInterest',
                'managed': False,
            },
        ),
    ]
