# Generated by Django 3.1.1 on 2020-09-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0009_comment_commentimage_qna_qnaimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
