# Generated by Django 3.1.1 on 2020-09-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0010_auto_20200922_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
    ]
