# Generated by Django 3.1.1 on 2020-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_auto_20200922_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritesite',
            fields=[
                ('favoritesiteidx', models.AutoField(db_column='favoriteSiteIdx', primary_key=True, serialize=False)),
                ('useridx', models.CharField(db_column='userIdx', max_length=45)),
                ('siteidx', models.CharField(db_column='siteIdx', max_length=45)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'favoriteSite',
                'managed': False,
            },
        ),
    ]
