# Generated by Django 3.1.1 on 2020-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0012_favoritesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritelecture',
            fields=[
                ('favoritelectureidx', models.AutoField(db_column='favoriteLectureIdx', primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'favoriteLecture',
                'managed': False,
            },
        ),
    ]
