# Generated by Django 3.1.1 on 2020-09-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0013_favoritelecture'),
        ('lecture', '0009_categoryinterest_lectureinfo_subcategoryinterest'),
    ]

    operations = [
    ]
