# Generated by Django 3.1.1 on 2020-11-24 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choiceidx', models.AutoField(db_column='choiceIdx', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('quizidx', models.IntegerField(db_column='quizIdx')),
                ('choicenum', models.IntegerField(db_column='choiceNum')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classidx', models.AutoField(db_column='classIdx', primary_key=True, serialize=False)),
                ('classname', models.CharField(db_column='className', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classmember',
            fields=[
                ('classmemberidx', models.AutoField(db_column='classmemberIdx', primary_key=True, serialize=False)),
                ('progress', models.IntegerField()),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'classMember',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classtag',
            fields=[
                ('classtagidx', models.AutoField(db_column='classTagIdx', primary_key=True, serialize=False)),
                ('tagname', models.CharField(db_column='tagName', max_length=20)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'classTag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelidx', models.AutoField(db_column='levelIdx', primary_key=True, serialize=False)),
                ('levelname', models.CharField(blank=True, db_column='levelName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Siteinfo',
            fields=[
                ('siteidx', models.AutoField(primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'siteInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('useridx', models.AutoField(db_column='userIdx', primary_key=True, serialize=False)),
                ('profileimg', models.CharField(blank=True, db_column='profileImg', max_length=45, null=True)),
                ('nickname', models.CharField(db_column='nickName', max_length=45)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'userInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userinfo', models.OneToOneField(db_column='userIdx', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='class.userinfo')),
                ('userpwd', models.CharField(db_column='userPwd', max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=20)),
                ('school', models.CharField(blank=True, max_length=30, null=True)),
                ('job', models.CharField(blank=True, max_length=1, null=True)),
                ('isblocked', models.CharField(db_column='isBlocked', max_length=1)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lectureidx', models.AutoField(db_column='lectureIdx', primary_key=True, serialize=False)),
                ('lecturename', models.CharField(db_column='lectureName', max_length=60)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('lecturelink', models.TextField(db_column='lectureLink')),
                ('thumburl', models.TextField(blank=True, db_column='thumbUrl', null=True)),
                ('lecturer', models.CharField(blank=True, max_length=300, null=True)),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
                ('level', models.ForeignKey(db_column='level', on_delete=django.db.models.deletion.CASCADE, to='class.level')),
                ('siteinfo', models.ForeignKey(db_column='siteidx', on_delete=django.db.models.deletion.CASCADE, to='class.siteinfo')),
            ],
        ),
    ]
