# Generated by Django 3.1.1 on 2020-11-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('classidx', models.AutoField(db_column='classIdx', primary_key=True, serialize=False)),
                ('classname', models.CharField(db_column='className', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
