# Generated by Django 3.1.1 on 2020-11-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20201124_0229'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='study',
            table='study',
        ),
    ]
