# Generated by Django 3.1.1 on 2020-11-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_auto_20201124_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'managed': False},
        ),
    ]
