# Generated by Django 3.1.1 on 2020-11-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_auto_20201124_1219'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lecture',
            table='lecture',
        ),
    ]
