# Generated by Django 3.1.1 on 2020-09-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelidx', models.AutoField(db_column='levelIdx', primary_key=True, serialize=False)),
                ('levelname', models.CharField(blank=True, db_column='levelName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('useridx', models.AutoField(db_column='userIdx', primary_key=True, serialize=False)),
                ('profileimg', models.CharField(blank=True, db_column='profileImg', max_length=45, null=True)),
                ('nickname', models.CharField(db_column='nickName', max_length=45)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'userInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userinfo', models.OneToOneField(db_column='userIdx', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.userinfo')),
                ('userpwd', models.CharField(db_column='userPwd', max_length=45)),
                ('gender', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=20)),
                ('school', models.CharField(blank=True, max_length=30, null=True)),
                ('job', models.CharField(blank=True, max_length=1, null=True)),
                ('major', models.CharField(blank=True, max_length=1, null=True)),
                ('isblocked', models.CharField(db_column='isBlocked', max_length=1)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
    ]
