# Generated by Django 3.1.1 on 2020-09-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryidx', models.AutoField(db_column='categoryIdx', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(db_column='categoryName', max_length=20)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoryinterest',
            fields=[
                ('categoryinterestidx', models.AutoField(db_column='categoryInterestIdx', primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'categoryInterest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategoryidx', models.AutoField(db_column='subCategoryIdx', primary_key=True, serialize=False)),
                ('subcategoryname', models.CharField(db_column='subCategoryName', max_length=20)),
            ],
            options={
                'db_table': 'subCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategoryinterest',
            fields=[
                ('subcategoryinterestidx', models.AutoField(db_column='subCategoryInterestIdx', primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('isdeleted', models.CharField(db_column='isDeleted', max_length=1)),
            ],
            options={
                'db_table': 'subCategoryInterest',
                'managed': False,
            },
        ),
    ]
