# Generated by Django 3.1.1 on 2020-11-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookidx', models.AutoField(db_column='bookIdx', primary_key=True, serialize=False)),
                ('booktitle', models.TextField(db_column='bookTitle')),
                ('link', models.TextField()),
                ('thumbnail', models.TextField()),
                ('site', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
    ]
